# This file was generated by GoReleaser. DO NOT EDIT.
cask "intervals" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5d8ab541f486649fc846055a91cd62304919612798d5fd1de232e623afea6e5a"
      url "https://github.com/glebmish/intervals-icu-cli/releases/download/v#{version}/intervals-icu-cli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b9b08cfbd0a4fe100303ec063e9714426bff729fc7c39fef9dde93fd12cf0c4b"
      url "https://github.com/glebmish/intervals-icu-cli/releases/download/v#{version}/intervals-icu-cli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3b909ac8aca8ab5ffdddca0bdd8f846a83dd023ab0fbc9eda1bc94100e4e06fb"
      url "https://github.com/glebmish/intervals-icu-cli/releases/download/v#{version}/intervals-icu-cli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "990303cf9e6561b2f0c270deab7577dd9ef4e3314b9a48b54c98085b52a0ea29"
      url "https://github.com/glebmish/intervals-icu-cli/releases/download/v#{version}/intervals-icu-cli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "intervals"
  desc "CLI for the intervals.icu training analytics API"
  homepage "https://github.com/glebmish/intervals-icu-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "intervals"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/intervals"]
    end
  end

  # No zap stanza required

end
