# This file was generated by GoReleaser. DO NOT EDIT.
cask "intervals" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "6149b6e2c986e9ca83508912e1eafcfa86e12398a263e6abc962d9f1a1f42424"
      url "https://github.com/glebmish/intervals-icu-cli/releases/download/v#{version}/intervals-icu-cli_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c335082a0954e68f11fc9459b7fb96aac08a9637a4bcad322ffc4bc1ebcf7a52"
      url "https://github.com/glebmish/intervals-icu-cli/releases/download/v#{version}/intervals-icu-cli_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ce8bc3173d8aef3c1f481f78f4c0d11fbe75e389f99b89efcc6818237814aa9"
      url "https://github.com/glebmish/intervals-icu-cli/releases/download/v#{version}/intervals-icu-cli_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3f97ce7857b35b4512cc9db0304d172b4b7bc923220966318bccdbaea34485fc"
      url "https://github.com/glebmish/intervals-icu-cli/releases/download/v#{version}/intervals-icu-cli_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "intervals"
  desc "CLI for the intervals.icu training analytics API"
  homepage "https://github.com/glebmish/intervals-icu-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "intervals"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/intervals"]
    end
  end

  # No zap stanza required

end
