# This file was generated by GoReleaser. DO NOT EDIT.
cask "ynab" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "87bfea9c310e1a510f19a6e7732ce92956be110b6b74378aa62ce2c4e0829332"
      url "https://github.com/glebmish/ynab-cli/releases/download/v#{version}/ynab-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "898495b02166b38aa1b58fca5907072fe658c5f202f46a20190f0b1231c9e770"
      url "https://github.com/glebmish/ynab-cli/releases/download/v#{version}/ynab-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f55107aec75a7d5af460853d6b7b8e807f0eb4cb11040450d96983966324d6e"
      url "https://github.com/glebmish/ynab-cli/releases/download/v#{version}/ynab-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c520789386ca4c4191334ac068344c97a3c256a554fbe297aa587de7006310fc"
      url "https://github.com/glebmish/ynab-cli/releases/download/v#{version}/ynab-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ynab"
  desc "Command-line interface for the YNAB (You Need A Budget) API"
  homepage "https://github.com/glebmish/ynab-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ynab"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ynab"]
    end
  end

  # No zap stanza required

end
