# This file was generated by GoReleaser. DO NOT EDIT.
cask "ynab" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "801d5c8884f6487cac93f0a91550e01d58f934356b1b1cdc12572fe0a6dd9ec9"
      url "https://github.com/glebmish/ynab-cli/releases/download/v#{version}/ynab-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "206886544c5401d260009bd1c58b4ed4bdfb145cbcf79ec83638f08eeca994e8"
      url "https://github.com/glebmish/ynab-cli/releases/download/v#{version}/ynab-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "98402d6f6afd31b696b82d246091f93e2b42ba6e5d659ed0ddd39f68bb80db59"
      url "https://github.com/glebmish/ynab-cli/releases/download/v#{version}/ynab-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6912ed7e159adc3f42f77afbf83dec4ee60d947c9e3ecb56c4ddefcfcd70385b"
      url "https://github.com/glebmish/ynab-cli/releases/download/v#{version}/ynab-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ynab"
  desc "Command-line interface for the YNAB (You Need A Budget) API"
  homepage "https://github.com/glebmish/ynab-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ynab"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ynab"]
    end
  end

  # No zap stanza required

end
